version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    resource_class: catherinepope/docker
    steps:
      - run: echo "Hellooooo, I'm running on Runners with Docker!"
