version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    # machine: true
    resource_class: catherinepope/agent
    steps:
      - run: echo "Hellooooooo, I'm running on Runners with Container Agent!"
